'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{EventEmitter}=require('node:events'),Service=require('../service');
class FakeCloud{constructor(credentials,session){this.credentials=credentials;this.session=session;}async login(){if(this.credentials.password==='bad')throw Error('Anker API 26108');this.session={auth_token:'fictional-secret-token',user_id:'user',token_expires_at:9999999999};}async devices(){return [{device_sn:'test-sn',alias_name:'Test charger'}];}async mqttInfo(){return {};}async theme(id){return {id:Number(id),hash:1,url:'https://example.invalid/theme'};}}
class FakeConnection extends EventEmitter{constructor(){super();this.states=new Map();this.commands=[];}async connect(){this.client={connected:true};const t=Date.now();this.states.set('test-sn',{ports:{C1:{power:36,voltage:12,current:3,updated:t,active:true}},groups:{C1:{on:true}},settings:{mode:5,customProfile:[1,0,100,45,45,30,24],customProtocols:Array(12).fill(0)},updated:t,statusUpdated:t,total:null});}async control(sn,action,args){this.commands.push({sn,action,args});}async close(){this.client.connected=false;}}
const credentials={email:'test@example.invalid',password:'fictional-password-secret',region:'eu',country:'DE'};
test('standalone pairing, encrypted restart, separate counters, and rejected input need no Homey',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'anker-service-'));let s;const make=()=>new Service(dir,{CloudClass:FakeCloud,ConnectionClass:FakeConnection});try{s=make();await s.init();assert.equal(s.status().configured,false);assert.equal(s.overview().devices.length,0);await s.login(credentials);assert.equal(s.status().configured,true);assert.equal(s.overview().devices[0].name,'Test charger');const raw=await fs.readFile(path.join(dir,'account.enc'),'utf8');assert(!raw.includes(credentials.password));assert(!raw.includes('fictional-secret-token'));assert.equal((await fs.stat(path.join(dir,'account.enc'))).mode&0o777,0o600);assert(!JSON.stringify(s.overview()).includes(credentials.password));
 await assert.rejects(s.control({id:'test-sn',action:'limit',args:{port:'C1',value:101}}));await assert.rejects(s.control({id:'test-sn',action:'custom',args:{}}));assert.equal(s.connection.commands.length,0);const now=Date.now();s.energy('test-sn','C1').last=null;for(const t of [now-10000,now])s.sampleEnergy('test-sn',{ports:{C1:{power:36,updated:t}}});assert.equal(s.overview().devices[0].energy.C1.wh,.1);
 await s.control({id:'test-sn',action:'labels',args:{label_C1:'Laptop'}});const old=s.connection;await assert.rejects(s.login({...credentials,password:'bad'}));assert.equal(s.connection,old);assert.equal(s.status().connected,true);
 await s.close();s=make();await s.init();await s.connect();assert.equal(s.overview().devices[0].labels.label_C1,'Laptop');assert.equal(s.overview().devices[0].energy.C1.wh,.1);await s.control({id:'test-sn',action:'energy_reset',args:{port:'C1'}});assert.equal(s.overview().devices[0].energy.C1.wh,0);await s.control({id:'test-sn',action:'brightness',args:{value:80}});assert.equal(s.connection.commands.at(-1).action,'brightness');
 }finally{await s?.close();await fs.rm(dir,{recursive:true,force:true});}});
