'use strict';
const fs=require('node:fs/promises'),path=require('node:path');
const Cloud=require('./lib/cloud'),Connection=require('./lib/connection'),Vault=require('./lib/vault'),Energy=require('./lib/energy'),limits=require('./lib/power-limit'),{command,GROUPS}=require('./lib/protocol'),themes=require('./lib/themes.json');
class AnkerService{
 constructor(dir,{CloudClass=Cloud,ConnectionClass=Connection}={}){this.dir=dir;this.CloudClass=CloudClass;this.ConnectionClass=ConnectionClass;this.vault=new Vault(dir);this.account=null;this.devices=[];this.records={};this.energies=new Map();this.connection=null;this.saving=Promise.resolve();this.retryAt=0;this.failures=0;this.closed=false;}
 async init(){await this.vault.init();this.account=await this.vault.read();try{this.records=JSON.parse(await fs.readFile(path.join(this.dir,'devices-state.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}if(this.account){this.devices=this.account.devices||[];this.connect().catch(()=>{});}this.health=setInterval(()=>{if(this.account&&!this.connecting&&Date.now()>=this.retryAt&&(!this.connection||!this.connection.client?.connected&&Date.now()-(this.connectedAt||0)>120000))this.connect().catch(()=>{});},15000);this.persistence=setInterval(()=>this.saveRecords().catch(()=>{}),5000);}
 status(){return {configured:!!this.account,email:this.account?.credentials.email||null,region:this.account?.credentials.region||null,country:this.account?.credentials.country||null,connected:!!this.connection?.client?.connected,reconnecting:!!this.connecting};}
 async login(credentials){if(this.connecting||this.loginBusy)throw Error('Подключение уже выполняется. Подождите.');if(!credentials||typeof credentials.email!=='string'||typeof credentials.password!=='string'||credentials.email.length>254||credentials.password.length>512||!credentials.email.includes('@')||!['eu','com'].includes(credentials.region)||!/^[A-Z]{2}$/.test(credentials.country||''))throw Error('Укажите почту, пароль, регион и код страны.');this.loginBusy=true;let candidate;
  try{const cloud=new this.CloudClass({email:credentials.email.trim(),password:credentials.password,region:credentials.region,country:credentials.country});await cloud.login();const devices=await cloud.devices();if(!devices.length)throw Error('В этом аккаунте нет зарядки Anker Prime A2345. Проверьте регион.');const info=await cloud.mqttInfo();candidate=new this.ConnectionClass(info,devices);await candidate.connect();const account={credentials:cloud.credentials,session:cloud.session,devices};await this.vault.write(account);await this.connection?.close();this.account=account;this.cloud=cloud;this.devices=devices;this.attach(candidate);this.failures=0;this.retryAt=0;return {ok:true};}catch(e){await candidate?.close();throw this.friendly(e);}finally{this.loginBusy=false;}}
 friendly(e){if(e.code==='LIMIT_RANGE')return Error('Лимит USB-C задаётся с шагом 5 Вт. Для USB-A доступны 0, 15 и 24 Вт.');if(e.code==='LIMIT_BUDGET')return Error('Недостаточно общего бюджета мощности.');if(e.code==='PROFILE_MISSING')return Error('Зарядка ещё не передала пользовательский профиль. Попробуйте позже.');if(/^Anker API/.test(e.message))return Error('Anker отклонил вход. Проверьте логин, пароль и регион.');if(/Anker HTTP|connection failed|MQTT/.test(e.message))return Error('Не удалось подключиться к облаку Anker. Попробуйте позже.');return e;}
 attach(connection){this.connection=connection;this.connectedAt=Date.now();connection.on('state',(sn,s)=>this.sampleEnergy(sn,s));connection.on('offline',()=>{for(const e of this.energies.values())e.last=null;});for(const [sn,s] of connection.states)this.sampleEnergy(sn,s);}
 connect(){if(this.connecting)return this.connecting;if(!this.account||this.closed)return Promise.resolve();this.retryAt=Date.now()+60000;this.connecting=(async()=>{await this.connection?.close();this.connection=null;this.cloud=new this.CloudClass(this.account.credentials,this.account.session);this.devices=await this.cloud.devices();const info=await this.cloud.mqttInfo();this.account={...this.account,session:this.cloud.session,devices:this.devices};await this.vault.write(this.account);const conn=new this.ConnectionClass(info,this.devices);try{await conn.connect();this.attach(conn);this.failures=0;}catch(e){await conn.close();throw e;}})().catch(e=>{this.failures++;this.retryAt=Date.now()+Math.min(600000,30000*2**this.failures);throw this.friendly(e);}).finally(()=>this.connecting=null);return this.connecting;}
 record(sn){return this.records[sn]||(this.records[sn]={labels:{},energy:{}});}
 energy(sn,port){const key=sn+':'+port;if(!this.energies.has(key))this.energies.set(key,new Energy(this.record(sn).energy[port]));return this.energies.get(key);}
 sampleEnergy(sn,s){for(const p of GROUPS){const e=this.energy(sn,p),values=p==='A'?[s.ports.A1,s.ports.A2]:[s.ports[p]],valid=values.every(v=>v&&Number.isFinite(v.power)&&Date.now()-v.updated<=30000);e.sample(valid?values.reduce((n,v)=>n+v.power,0):NaN,valid?Math.min(...values.map(v=>v.updated)):NaN);this.record(sn).energy[p]=e.snapshot();}}
 saveRecords(){const snapshot=JSON.stringify(this.records);this.saving=this.saving.catch(()=>{}).then(async()=>{await fs.writeFile(path.join(this.dir,'devices-state.tmp'),snapshot,{mode:0o600});await fs.rename(path.join(this.dir,'devices-state.tmp'),path.join(this.dir,'devices-state.json'));});return this.saving;}
 overview(){return {configured:!!this.account,themes,timezone:process.env.TZ||'Europe/Moscow',devices:this.devices.map(d=>{const sn=d.device_sn,s=this.connection?.states.get(sn),value=s?structuredClone(s):{ports:{},groups:{},settings:{},updated:0,total:null},stale=!this.connection?.client?.connected||!s||Date.now()-s.updated>45000,labels={...this.record(sn).labels},theme=String(value.settings.themeId||'');labels.display_theme=(value.settings.clockSettings&6)===2&&themes[theme]?theme:'other';labels.port_priority=String(['C1','C2','C3','C4'].reduce((sum,p,i)=>sum+(value.groups[p]?.priority===2?1<<i:0),0));return {id:sn,name:d.alias_name||'Anker Prime',...value,stale,labels,energy:Object.fromEntries(GROUPS.map(p=>[p,this.energy(sn,p).snapshot()]))};})};}
 async control(body){if(!body||!this.devices.some(d=>d.device_sn===body.id))throw Error('Неизвестная зарядка.');const sn=body.id,a=body.args||{},action=body.action;
  if(action==='labels'){for(const [k,v] of Object.entries(a))if(!/^label_(C[1-4]|A[12])$/.test(k)||typeof v!=='string'||v.length>40)throw Error('Некорректное название порта.');Object.assign(this.record(sn).labels,Object.fromEntries(Object.entries(a).map(([k,v])=>[k,v.trim()])));await this.saveRecords();return {ok:true};}
  if(action==='energy_reset'){if(!GROUPS.includes(a.port))throw Error('Неизвестный порт.');const e=this.energy(sn,a.port);e.reset();this.record(sn).energy[a.port]=e.snapshot();await this.saveRecords();return {ok:true};}
  if(this.overview().devices.find(d=>d.id===sn).stale)throw Error('Зарядка не на связи.');
  try{if(action==='limit_preview')return limits.prepare(this.connection.states.get(sn).settings,a,true);if(action==='theme'){if(!Object.hasOwn(themes,String(a.id)))throw Error('Неизвестный скринсейвер.');const theme=await this.cloud.theme(a.id);this.account.session=this.cloud.session;await this.vault.write(this.account);await this.connection.control(sn,'theme',theme);return {ok:true};}
   if(action==='limit')limits.validate(a.port,a.value);else if(action==='mode'&&a.value===5){}else if(['power','timer','mode','brightness','timeout','clock','knob','priority','schedule','clock_holiday','clock_schedule'].includes(action))command(action,a);else throw Error('Неподдерживаемая команда.');await this.connection.control(sn,action,a);return {ok:true};
  }catch(e){throw this.friendly(e);}
 }
 async close(){this.closed=true;clearInterval(this.health);clearInterval(this.persistence);await this.connecting?.catch(()=>{});await this.connection?.close();await this.saveRecords();}
}
module.exports=AnkerService;
